"""
Django settings for eureka project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6sgm4+==m_$9@k1vr55oa8%b#!5h(+=ci2zi7h6)-w!hqsrhcw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eureka.apps.EurekaConfig',
    'rest_framework',
    'rest_framework.authtoken', 
    'drf_spectacular',
    'djangoviz'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eureka.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eureka.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'eureka',
        'USER': 'eureka',
        'PASSWORD': 'eureka',
        'HOST': 'db',
        'PORT': '5432',
    }
}

AUTH_USER_MODEL = 'eureka.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ ]
"""
{
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
},
"""

AUTHENTICATION_BACKENDS = [
    'eureka.backends.OIDCAuthenticationBackend',   # OpenID Connect authentication
    'eureka.backends.EmailBackend',                # Your custom email authentication backend
    'django.contrib.auth.backends.ModelBackend',   # Django's default (for login by 'username_field')
]

# OpenID Connect Configuration (EGI Check-In)
OIDC_ISSUER = 'https://aai.egi.eu/auth/realms/egi'
OIDC_JWKS_URI = 'https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/certs'
# OIDC_CLIENT_ID = 'your-client-id-here'  # TODO: Set this in production or via environment variable


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication', # For browser-based auth
        'rest_framework.authentication.BasicAuthentication',   # For basic auth
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # Require authentication by default
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # Link to spectacular
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Eureka Tour Builder API',
    'DESCRIPTION': '''A comprehensive API for building and managing interactive tours with multilingual support.

## Features
- **Project Management**: Create and manage tour projects with group-based permissions
- **Tour Creation**: Build interactive tours with customizable routes and content
- **POI Management**: Manage Points of Interest with rich metadata and multilingual content
- **Asset Management**: Handle media assets (images, videos, audio) with automatic thumbnail generation
- **User & Group Management**: Role-based access control with personal and shared groups

## Authentication
The API uses token-based authentication. Include your token in the Authorization header:
```
Authorization: Token your_token_here
```

## Data Format
All multilingual content is stored in JSON format, allowing for flexible language support.''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PUBLIC': True,
    'AUTO_TAG_BEHAVIOR': 'none',
    'COMPONENT_SPLIT_REQUEST': True,
    'MARKDOWN_ENABLED': True,
    'SWAGGER_UI_SETTINGS': {
        'docExpansion': 'list',
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 1,
    },
    'TAGS': [
        {
            'name': 'User',
            'description': 'User authentication, account management, and user-related operations including login, signup, and user listing.'
        },
        {
            'name': 'Group Management',
            'description': 'Manage user groups and group membership for collaborative projects.'
        },
        {
            'name': 'Projects',
            'description': 'Create and manage tour projects with group-based permissions and metadata.'
        },
        {
            'name': 'Assets',
            'description': 'Manage media assets (images, videos, audio) with automatic thumbnail generation and metadata. Supports creation for projects or POIs with automatic source asset selection.'
        },
        {
            'name': 'Tours',
            'description': 'Build and manage interactive tours with customizable routes, content, and multilingual support.'
        },
        {
            'name': 'Points of Interest',
            'description': 'Manage Points of Interest (POIs) with rich metadata, coordinates, and multilingual content.'
        }
    ],
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development server'
        }
    ],
    'SECURITY': [
        {
            'Token': []
        }
    ],
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Token-based authentication. Format: Token your_token_here'
        }
    },
    'COMPONENTS': {
        'schemas': {
            'MultilingualText': {
                'type': 'object',
                'description': 'Multilingual text content with locales wrapper for easy identification',
                'properties': {
                    'locales': {
                        'type': 'object',
                        'description': 'Language codes as keys with text content as values',
                        'properties': {
                            'en': {
                                'type': 'string',
                                'description': 'English text content',
                                'example': 'Welcome to our tour'
                            },
                            'de': {
                                'type': 'string',
                                'description': 'German text content',
                                'example': 'Willkommen zu unserer Tour'
                            },
                            'fr': {
                                'type': 'string',
                                'description': 'French text content',
                                'example': 'Bienvenue à notre visite'
                            },
                            'es': {
                                'type': 'string',
                                'description': 'Spanish text content',
                                'example': 'Bienvenido a nuestro tour'
                            }
                        },
                        'additionalProperties': {
                            'type': 'string',
                            'description': 'Additional language codes and their text content'
                        }
                    }
                },
                'required': ['locales'],
                'example': {
                    'locales': {
                        'en': 'Welcome to our tour',
                        'de': 'Willkommen zu unserer Tour',
                        'fr': 'Bienvenue à notre visite',
                        'es': 'Bienvenido a nuestro tour'
                    }
                }
            }
        }
    }
}
