# Generated by Django 5.2.3 on 2025-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='thumbnail_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
