# Generated by Django 5.2.3 on 2025-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0004_update_project_fields_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='real_height_meters',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Real-world height of the asset in meters (for map images and 3D objects)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='real_width_meters',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Real-world width of the asset in meters (for map images and 3D objects)', max_digits=10, null=True),
        ),
    ]
