# Generated by Django 5.2.3 on 2025-06-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0005_add_real_world_dimensions_to_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eureka.tour'),
        ),
    ]
