# Generated by Django 5.2.3 on 2025-06-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0006_add_tour_to_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='real_height_meters',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='real_width_meters',
        ),
    ]
