# Generated by Django 5.2.7 on 2025-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0007_remove_real_world_dimensions_from_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='distanceMeters',
            field=models.PositiveIntegerField(blank=True, help_text='Total distance of the tour in meters', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='durationMinutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration of the tour in minutes', null=True),
        ),
    ]
