# Generated by Django 5.2.7 on 2025-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0008_tour_distancemeters_tour_durationminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='locales',
            field=models.JSONField(default=list, help_text="Supported language codes for this project, e.g. ['en', 'fr', 'it']"),
        ),
        migrations.AddField(
            model_name='tour',
            name='locales',
            field=models.JSONField(default=list, help_text="Supported language codes for this tour, e.g. ['en', 'fr', 'it']"),
        ),
    ]
