# Generated by Django 5.2.7 on 2025-11-29 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0009_project_locales_tour_locales'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(help_text='Latitude')),
                ('long', models.FloatField(help_text='Longitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='language',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='poi',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='source_asset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='thumbnail_data',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_latitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_longitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='min_latitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='min_longitude',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='bounding_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='eureka.boundingbox'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='northeast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundingbox_ne', to='eureka.coordinates'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='southwest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundingbox_sw', to='eureka.coordinates'),
        ),
        migrations.AddField(
            model_name='poi',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eureka.coordinates'),
        ),
        migrations.CreateModel(
            name='POIAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('description', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=512)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=6)),
                ('view_in_ar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eureka.poi')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_assets', to='eureka.asset')),
            ],
        ),
    ]
