# Generated by Django 5.2.7 on 2025-11-29 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0010_boundingbox_coordinates_remove_asset_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='bounding_box',
        ),
        migrations.AddField(
            model_name='poi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='long',
            field=models.FloatField(blank=True, help_text='Longitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_lat',
            field=models.FloatField(blank=True, help_text='Maximum latitude of bounding box', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_long',
            field=models.FloatField(blank=True, help_text='Maximum longitude of bounding box', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='min_lat',
            field=models.FloatField(blank=True, help_text='Minimum latitude of bounding box', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='min_long',
            field=models.FloatField(blank=True, help_text='Minimum longitude of bounding box', null=True),
        ),
    ]
