# Generated by Django 5.2.7 on 2025-11-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0011_remove_poi_coordinates_remove_tour_bounding_box_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoundingBox',
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
