# Generated by Django 5.2.7 on 2025-11-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0012_delete_boundingbox_delete_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poiasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
