# Generated by Django 5.2.7 on 2025-11-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0013_asset_updated_at_poiasset_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='distanceMeters',
            new_name='distance_meters',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='durationMinutes',
            new_name='duration_minutes',
        ),
    ]
