# Generated by Django 5.2.7 on 2025-12-01 09:16

import eureka.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0014_rename_distancemeters_tour_distance_meters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='long',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_lat',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_long',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='min_lat',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='min_long',
        ),
        migrations.AddField(
            model_name='asset',
            name='coordinates',
            field=eureka.models.fields.Coordinates(blank=True, help_text='Geographic coordinates (optional)', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='coordinates',
            field=eureka.models.fields.Coordinates(blank=True, help_text='Geographic coordinates', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='external_links',
            field=eureka.models.fields.ExternalLinks(blank=True, help_text='Multilingual external links (quiz/blog)', null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='radius',
            field=models.PositiveIntegerField(default=20, help_text='Radius in meters (default: 20)'),
        ),
        migrations.AddField(
            model_name='poi',
            name='title',
            field=eureka.models.fields.MultilingualTextField(),
        ),
        migrations.AddField(
            model_name='poiasset',
            name='coordinates',
            field=eureka.models.fields.Coordinates(blank=True, help_text='Geographic coordinates (optional)', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='bounding_box',
            field=eureka.models.fields.BoundingBox(blank=True, help_text='Geographic bounding box of the tour', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=eureka.models.fields.MultilingualTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=eureka.models.fields.MultilingualTextField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=eureka.models.fields.MultilingualTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='description',
            field=eureka.models.fields.MultilingualTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poiasset',
            name='description',
            field=eureka.models.fields.MultilingualTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poiasset',
            name='title',
            field=eureka.models.fields.MultilingualTextField(),
        ),
        migrations.AlterField(
            model_name='poiasset',
            name='url',
            field=eureka.models.fields.MultilingualTextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=eureka.models.fields.MultilingualTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=eureka.models.fields.MultilingualTextField(),
        ),
    ]
