# Generated by Django 5.2.7 on 2025-12-01 21:33

import eureka.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0015_remove_poi_lat_remove_poi_long_remove_poi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiasset',
            name='linked_asset',
            field=eureka.models.fields.LinkedAsset(blank=True, help_text='Multilingual linked asset with title and URL', null=True),
        ),
    ]
