# Generated by Django 5.2.7 on 2025-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0016_poiasset_linked_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
