# Generated by Django 5.2.9 on 2025-12-03 16:32

import eureka.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0017_rename_login_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=eureka.models.fields.MultilingualTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=eureka.models.fields.MultilingualTextField(),
        ),
    ]
