# Generated by Django 5.2.9 on 2025-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0018_alter_project_description_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='guided',
            field=models.BooleanField(default=False, help_text='Whether this POI is guided'),
        ),
    ]
