# Generated by Django 5.2.9 on 2025-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0019_poi_guided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='guided',
        ),
        migrations.AddField(
            model_name='tour',
            name='guided',
            field=models.BooleanField(default=False, help_text='Whether this tour is guided'),
        ),
    ]
