# Generated by Django 5.2.9 on 2025-12-06 09:36

import eureka.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0021_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='center',
            field=eureka.models.fields.Coordinates(blank=True, help_text='Geographic center of the tour', null=True),
        ),
    ]
