# Generated by hand on 2025-12-07
# Data migration to populate the center field for existing tours

from django.db import migrations


def populate_tour_centers(apps, schema_editor):
    """
    Populate the center field for all existing tours that have POIs.
    This ensures existing tours have their center calculated.
    """
    Tour = apps.get_model('eureka', 'Tour')

    # Get all tours
    tours = Tour.objects.all()

    for tour in tours:
        # Get all POIs for this tour
        pois = tour.pois.all()

        if not pois.exists():
            continue

        # Collect all valid coordinates from POIs
        lat_sum = 0
        long_sum = 0
        valid_count = 0

        for poi in pois:
            if poi.coordinates:
                lat = poi.coordinates.get('lat')
                long = poi.coordinates.get('long')

                if lat is not None and long is not None:
                    lat_sum += lat
                    long_sum += long
                    valid_count += 1

        # Calculate and set center if we found valid coordinates
        if valid_count > 0:
            tour.center = {
                "lat": lat_sum / valid_count,
                "long": long_sum / valid_count
            }
            tour.save(update_fields=['center'])


def reverse_populate_tour_centers(apps, schema_editor):
    """
    Reverse migration - clear all tour centers.
    """
    Tour = apps.get_model('eureka', 'Tour')
    Tour.objects.all().update(center=None)


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0022_tour_center'),
    ]

    operations = [
        migrations.RunPython(populate_tour_centers, reverse_populate_tour_centers),
    ]
