# Generated by Django 5.2.9 on 2025-12-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0023_populate_tour_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiasset',
            name='ar_placement',
            field=models.CharField(choices=[('free', 'Free'), ('ground', 'Ground')], default='free', max_length=6),
        ),
    ]
