# Generated by Django 6.0 on 2026-01-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0024_poiasset_ar_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiasset',
            name='spawn_radius',
            field=models.FloatField(default=5),
        ),
    ]
