# Generated by Django 6.0.1 on 2026-01-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0025_add_spawn_radius_to_poi_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poiasset',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poi_assets', to='eureka.asset'),
        ),
    ]
