# Generated by Django 6.0.3 on 2026-03-19 13:03

import eureka.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0029_rename_coordinates_to_georeference'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiasset',
            name='model_transform',
            field=eureka.models.fields.ModelTransform(blank=True, help_text='3D transform with position, rotation, and scale (optional)', null=True),
        ),
    ]
