# Generated by Django 6.0.3 on 2026-04-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0032_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poi_thumbnails', to='eureka.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_covers', to='eureka.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_logos', to='eureka.image'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_covers', to='eureka.image'),
        ),
    ]
